package com.flashdash.model;

public enum ActivityType {
    ACCOUNT_REGISTRATION,
    ACCOUNT_CONFIRMATION,
    ACCOUNT_LOGIN,
    ACCOUNT_UPDATED,
    ACCOUNT_DELETED,
    GAME_STARTED,
    GAME_FINISHED,
    DECK_CREATED,
    DECK_UPDATED,
    DECK_DELETED,
    QUESTION_CREATED,
    QUESTION_UPDATED,
    QUESTION_DELETED,
    FRIEND_INVITE_SENT,
    FRIEND_INVITE_RESPONDED,
    FRIEND_DELETED
}
