package com.flashdash.model;

public enum ActivityType {
    REGISTRATION,
    ACCOUNT_CONFIRMATION,
    LOGIN,
    GAME_STARTED,
    GAME_FINISHED,
    DECK_CREATED,
    DECK_UPDATED,
    DECK_DELETED,
    QUESTION_CREATED,
    QUESTION_UPDATED,
    QUESTION_DELETED,
    FRIEND_INVITE_SENT,
    FRIEND_INVITE_RESPONDED
}
